### ISSUE TITLE
Use the right indentation

### ISSUE THREAD

**Issue by graffsknarr** [mile95/datastrukturer#2]
Hello Freidrich

please use correct indentation on your code for example:
else if(bids.get(i).type.equals("NS")) {
        if(!sellqueue.change(bids.get(i))) {
          System.err.println("Det gar ej att andra bud som inte existerar 2");
      }
      }

should be:
else if(bids.get(i).type.equals("NS")) {
        if(!sellqueue.change(bids.get(i))) {
          System.err.println("Det gar ej att andra bud som inte existerar 2");
      }
}

best regards
graffsknarr

**Comment by mile95** [comment]
Thanks m8, very helpful!
